---
- name: Find latest backups
  local_action:
    module: find
    paths: "{{ local_bkup_path  }}"
    file_type: directory
  register: dirs

- name: Sort dirs
  set_fact:
    sorted_dirs: "{{ dirs.files | sort(attribute='ctime') }}"

- name: Find local backup files
  local_action:
    module: find
    path: "{{ dirs.files[-1].path }}/{{ database }}"
  register: test

- name: Copy backup files to server
  copy:
    src: "{{ item.path }}"
    dest: "{{ remote_bkup_path }}/{{ database }}/"
  with_items: "{{ test.files }}"

- name: Dump the database
  command: >
    mongorestore
    --uri="mongodb://{{ server_ip }}:{{ port }}"
    -u "{{ user }}"
    --authenticationDatabase "{{ auth_database }}"
    -p "{{ password }}"
    "{{ remote_bkup_path }}"

- name: Remove backups from the server
  file:
    path: "{{ remote_bkup_path }}"
    state: absent
