---
- name: Find backups
  local_action:
    module: find
    paths: "{{ local_bkup_path  }}"
    file_type: directory
  register: dirs

- name: Sort backups by age
  set_fact:
    sorted_dirs: "{{ dirs.files | sort(attribute='ctime') }}"

- name: Copy latest backup files to server
  copy:
    src: "{{ dirs.files[-1].path }}/"
    dest: "{{ remote_bkup_path }}"

- name: Restore the database
  command: >
    mongorestore
    --uri="mongodb://{{ server_ip }}:{{ port }}"
    -u "{{ user }}"
    --authenticationDatabase "{{ auth_database }}"
    -p "{{ password }}"
    "{{ remote_bkup_path }}/"

- name: Remove backups from the server
  file:
    path: "{{ remote_bkup_path }}"
    state: absent
